version: 2
jobs:
    build:
        docker:
            - image: circleci/python:3.7.4
        steps:
            - checkout
            - run: 
                command: |
                    sudo pip install -r requirements.txt
            - run:
                command: |
                    pytest --junitxml=test-results/junit.xml
            - store_test_results:
                path: test-results
            - run:
                command: |
                    python setup.py verify
            - run:
                name: init .pypirc
                command: |
                    echo -e "[pypi]" >> ~/.pypirc
                    echo -e "username = doodoroma" >> ~/.pypirc
                    echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            - run:
                name: create packages
                command: |
                    python setup.py sdist
                    pip install twine
                    twine upload dist/*

        